### PR TITLE
style more in alignment with figma for file menu and icon buttons

### LINKED ISSUE #533: Polish file menu
Based on figma, polish file menu
1. spacing
2. margins

### PR DESCRIPTION
**Pull request by bthaile**
Closes: #533 

## Description

styling icon buttons
style file menu to be more alignment with figma

image

______

For contributor use:

- [x] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/onflow/flow-playground/blob/master/CONTRIBUTING.md))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [standards mentioned here](https://github.com/onflow/flow-playground/blob/master/CONTRIBUTING.md).
- [ ] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Added appropriate labels

### CODE REVIEW

**Comment by devbugging** [comment]
Don't want to be anoying but the menu is still not spaced correctly. The issue is that groups (contracts, transactions...) have the same margin between each other than the files. In design grouping is very important and if you compare the design you will notice the groups have a bigger spacing between each other than the items.

**Comment by bthaile** [comment]
in the design there is 16px between folder and first item and 12px space between items. I missed the space above the folder name. I'll fix
Also need to fix left spacing so the file icon is aligned with folder name.

**Comment by bthaile** [comment]
updated icon filename alignment to be under folder name.

**Comment by devbugging** [comment]
Feels great now! thanks

**Review by devbugging — APPROVED** [review]

**Pull request merged**
