### PR TITLE
Update flow-js-testing handlebars templates to @onflow-flow-js-testing@0.3.0-alpha.14

### LINKED ISSUE #276: Update flow-js-testing to @onflow/flow-js-testing@0.3.0-alpha.14
**Is your feature request related to a problem? Please describe.**
The flow-js-testing version for unit tests generated by the playground is fairly outdated.  This should be brought to date with the latest version.

Additionally, flow-js-testing has moved to a different NPM registry (@onflow/flow-js-testing).  This should also be updated.

**Describe the solution you'd like**
Update to @onflow/flow-js-testing 

**Additional context**
Linked issue in flow-js-testing repo: https://github.com/onflow/flow-js-testing/issues/141

### PR DESCRIPTION
**Pull request by jribbink**
Closes: #276 

## Description

______

For contributor use:

- [x] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/onflow/flow-playground/blob/master/CONTRIBUTING.md))
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x] Code follows the [standards mentioned here](https://github.com/onflow/flow-playground/blob/master/CONTRIBUTING.md).
- [x] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

**Comment by devbugging** [comment]
@alse @MrDSGC please take a look into this one if it's still relevant

**Comment by alse** [comment]
@jribbink I'm seeing this error when exporting a project. It's not happening on the staging branch. src/templates/js/scriptUnitTest.hbs:20

```
Uncaught (in promise) SyntaxError: Unexpected token, expected "," (20:11) (at parser-babel.js?6103:1:1)
  18 |             code,
  19 |             
> 20 |         });
     |           ^
  21 |     )
  22 | 
  23 |     // Add your expectations here
    at t (parser-babel.js?6103:1:1)
    at Object.eval [as parse] (parser-babel.js?6103:1:1)
    at Object.parse (standalone.js?325b:15:1)
    at ts (standalone.js?325b:15:1)
    at us (standalone.js?325b:15:1)
    at eval (standalone.js?325b:55:1)
    at Object.format (standalone.js?325b:55:1)
    at prettify (generator.ts?e988:18:1)
    at generateScriptUnitTest (generator.ts?e988:251:1)
    at eval (generator.ts?e988:288:1)
    ```

**Comment by jribbink** [comment]
> @jribbink I'm seeing this error when exporting a project. It's not happening on the staging branch. src/templates/js/scriptUnitTest.hbs:20
> 
> ```
> Uncaught (in promise) SyntaxError: Unexpected token, expected "," (20:11) (at parser-babel.js?6103:1:1)
>   18 |             code,
>   19 |             
> > 20 |         });
>      |           ^
>   21 |     )
>   22 | 
>   23 |     // Add your expectations here
>     at t (parser-babel.js?6103:1:1)
>     at Object.eval [as parse] (parser-babel.js?6103:1:1)
>     at Object.parse (standalone.js?325b:15:1)
>     at ts (standalone.js?325b:15:1)
>     at us (standalone.js?325b:15:1)
>     at eval (standalone.js?325b:55:1)
>     at Object.format (standalone.js?325b:55:1)
>     at prettify (generator.ts?e988:18:1)
>     at generateScriptUnitTest (generator.ts?e988:251:1)
>     at eval (generator.ts?e988:288:1)
>     ```
> ```

Apologies, that should be fixed now.

**Comment by alse** [comment]
Thanks @jribbink , that fixed it. I followed the readme instructions to run the generated tests and I'm 6 were failing. Are they passing for you?

```
"execution error code 1006: [Error Code: 1006] invalid proposal key: public key 0 on account [...] does not have a valid signature: [Error Code: 1009] invalid envelope key: public key 0 on account [...] does not have a valid signature: signature is not valid"
```

flow cli version v0.39.3

**Comment by bthaile** [comment]
closing, will need to reevaluate after polish sprint and mvp testing

**Pull request closed without merging**
