### PR TITLE
Add Cadence Language Reference Link

### PR DESCRIPTION
**Pull request by MaxStalker**
Implements #111

### CODE REVIEW

**Comment by 10thfloor** [comment]
Nice :) Can we play around with the location? What about putting the icon near the cadence version number?

**Review by 10thfloor — CHANGES_REQUESTED** [review]
Can we play around with the location of the link? What about having it near or next to the cadence version number, or even, making the version number text the link (the whole thing: so **cadence version: 0.12.5** )

**Comment by MaxStalker** [comment]
> Can we play around with the location of the link? What about having it near or next to the cadence version number, or even, making the version number text the link (the whole thing: so **cadence version: 0.12.5** )

Well. we can, but it would sorta be hidden 🤔
How many users would discover it then? 🤷‍♂️

**Comment by 10thfloor** [comment]
> > Can we play around with the location of the link? What about having it near or next to the cadence version number, or even, making the version number text the link (the whole thing: so **cadence version: 0.12.5** )
> 
> Well. we can, but it would sorta be hidden 🤔
> How many users would discover it then? 🤷‍♂️

True, let's leave it in the header for now.

**Review by 10thfloor — APPROVED** [review]

**Pull request merged**
